### ISSUE TITLE
sudo pip3 install estnltk fails on Mac

### ISSUE THREAD

**Issue by andreskull** [estnltk/estnltk#27] opened 2015-09-18 07:36 UTC
While installing estnltk on Mac OsX I get the following error:

    In file included from include/fsc/fsc.h:6:
    include/fsc/stdfsc.h:78:3: error: Only Win32(CE), Unix and Mac are currently supported.
            #error Only Win32(CE), Unix and Mac are currently supported.
             ^

It seems that the installer does not understand that it runs on Mac. Some dependency is missing? Any help?

**Comment by tpetmanson** [comment] 2015-09-18 11:43
Duplicate of https://github.com/estnltk/estnltk/issues/19.

**Closed by tpetmanson** 2015-09-18 11:43 UTC
